### ISSUE TITLE
Suggestion /w Third Person Camera

### ISSUE THREAD

**Issue by Scarlaid** [r0yzer/perspektive#11]
Hi, first of all, love the mod because it has distancing setting instead of having only the free-look function, which is really convenient for flying around and swimming.
I find out that the mod is lacking one thing and it's the convenient for the config menu

My idea on this is one of the following:
- Holding a key (configurable) while using scroll wheel would change the camera distancing following a configurable tolerance (like if its 0.5 then every scrolling would give you 0.5 more distance, I guess)
- Allow to access the config menu through a hotkey (maybe improve the config menu?)

That's it, hope this would help for other people too.

**Comment by r0yzer** [comment]
hi, thanks for your ideas. as i have not much time and motivation right now i will probably add it sometime but i cannot say when. if someone else wants to do this go for it

**Comment by FlerBuster** [comment]
das hab ich mal gemacht not much time ago

**Comment by r0yzer** [comment]
i think i wont add the settings hotkey because i dont want to pollute the hotkeys even more, as you can just go to your mod menu which is not that complicated.
i added the scrolling thing without a hotkey in 1.3.1 because i also dont see the need for another hotkey, since you will most likely not be scrolling through your inventory while in freelook, you can choose in the settings if you want to block scrolling aswell
